# Generated by Django 3.2.9 on 2021-11-05 06:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(default='', max_length=60)),
                ('emp_id', models.CharField(default='', max_length=15)),
                ('emp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emp_mob', models.CharField(default='', max_length=15)),
                ('date', models.DateField(default=datetime.date(2021, 11, 5))),
                ('status', models.BooleanField(default=False)),
                ('check', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default='', max_length=75)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vis_name', models.CharField(default='', max_length=60)),
                ('vis_id', models.CharField(default='', max_length=15)),
                ('vis_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vis_mob', models.CharField(default='', max_length=15)),
                ('date', models.DateField(default=datetime.date(2021, 11, 5))),
                ('status', models.BooleanField(default=False)),
                ('check', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default='', max_length=75)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visiting', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitor_management.employee')),
            ],
        ),
    ]
