# Generated by Django 3.2.9 on 2022-01-21 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_management', '0002_alter_visitor_visiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 21)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 21)),
        ),
    ]
